import json

import pytest

from jhsymphony.tracker.base import TrackerClient
from jhsymphony.tracker.github import GitHubTracker


@pytest.fixture
def tracker(httpx_mock) -> GitHubTracker:
    return GitHubTracker(repo="owner/repo", label="jhsymphony", token="fake-token")


def _gh_issue(number: int, title: str, labels: list[str], state: str = "open") -> dict:
    return {
        "id": number * 1000,
        "number": number,
        "title": title,
        "state": state,
        "labels": [{"name": l} for l in labels],
    }


async def test_fetch_candidates(httpx_mock, tracker):
    httpx_mock.add_response(
        url="https://api.github.com/repos/owner/repo/issues?labels=jhsymphony&state=open&per_page=100",
        json=[
            _gh_issue(1, "Fix bug", ["jhsymphony"]),
            _gh_issue(2, "Add feature", ["jhsymphony", "use-claude"]),
        ],
    )
    issues = await tracker.fetch_candidates()
    assert len(issues) == 2
    assert issues[0].number == 1
    assert "use-claude" in issues[1].labels


async def test_fetch_candidates_empty(httpx_mock, tracker):
    httpx_mock.add_response(
        url="https://api.github.com/repos/owner/repo/issues?labels=jhsymphony&state=open&per_page=100",
        json=[],
    )
    issues = await tracker.fetch_candidates()
    assert issues == []


async def test_post_comment(httpx_mock, tracker):
    httpx_mock.add_response(
        url="https://api.github.com/repos/owner/repo/issues/1/comments",
        json={"id": 999},
        status_code=201,
    )
    await tracker.post_comment(1, "JHSymphony started working on this.")


async def test_create_pr(httpx_mock, tracker):
    httpx_mock.add_response(
        url="https://api.github.com/repos/owner/repo/pulls",
        json={"number": 10, "html_url": "https://github.com/owner/repo/pull/10"},
        status_code=201,
    )
    pr = await tracker.create_pr(
        title="fix: resolve bug #1",
        head="jhsymphony/issue-1",
        base="main",
        body="Auto-generated by JHSymphony",
    )
    assert pr["number"] == 10


async def test_tracker_protocol():
    assert issubclass(GitHubTracker, TrackerClient)
