from __future__ import annotations

from typing import Protocol, runtime_checkable

from jhsymphony.models import Issue


@runtime_checkable
class TrackerClient(Protocol):
    async def fetch_candidates(self) -> list[Issue]: ...
    async def post_comment(self, issue_number: int, body: str) -> None: ...
    async def create_pr(self, title: str, head: str, base: str, body: str) -> dict: ...
    async def add_labels(self, issue_number: int, labels: list[str]) -> None: ...
    async def remove_label(self, issue_number: int, label: str) -> None: ...
