from __future__ import annotations

from typing import Protocol, runtime_checkable

from jhsymphony.models import Issue, IssueState, Run, RunStatus, UsageRecord


@runtime_checkable
class Storage(Protocol):
    async def initialize(self) -> None: ...
    async def close(self) -> None: ...

    async def upsert_issue(self, issue: Issue) -> None: ...
    async def get_issue(self, issue_id: str) -> Issue | None: ...
    async def list_issues(self, state: IssueState | None = None) -> list[Issue]: ...
    async def update_issue_state(self, issue_id: str, state: IssueState) -> None: ...

    async def insert_run(self, run: Run) -> None: ...
    async def get_run(self, run_id: str) -> Run | None: ...
    async def update_run_status(self, run_id: str, status: RunStatus, error: str | None = None) -> None: ...
    async def list_active_runs(self) -> list[Run]: ...
    async def get_run_count_for_issue(self, issue_id: str) -> int: ...
    async def get_analysis_run(self, issue_id: str) -> Run | None: ...
    async def update_run_analysis_comment_id(self, run_id: str, comment_id: int) -> None: ...

    async def insert_event(self, run_id: str, seq: int, event_type: str, payload: dict) -> None: ...
    async def list_events(self, run_id: str, since_seq: int = 0) -> list[dict]: ...

    async def record_usage(self, record: UsageRecord) -> None: ...
    async def sum_daily_cost(self) -> float: ...
    async def sum_run_cost(self, run_id: str) -> float: ...

    async def acquire_lease(self, issue_id: str, owner_id: str, ttl_sec: int) -> bool: ...
    async def release_lease(self, issue_id: str) -> None: ...
    async def list_active_leases(self) -> list[dict]: ...
