from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any

from jhsymphony.providers.base import EventType, RunContext

logger = logging.getLogger(__name__)


@dataclass
class ReviewResult:
    pr_number: int
    pr_url: str
    review_text: str
    approved: bool


class Reviewer:
    def __init__(self, provider: Any, tracker: Any, auto_approve: bool = False) -> None:
        self._provider = provider
        self._tracker = tracker
        self._auto_approve = auto_approve

    async def review(
        self,
        issue_number: int,
        issue_title: str,
        branch: str,
        base: str,
        repo: str,
        workspace_path: str,
    ) -> ReviewResult:
        # Create PR
        pr = await self._tracker.create_pr(
            title=f"fix: {issue_title} (#{issue_number})",
            head=branch,
            base=base,
            body=f"Auto-generated by JHSymphony for issue #{issue_number}",
        )
        pr_number = pr["number"]
        pr_url = pr.get("html_url", "")

        # Run review agent
        review_prompt = (
            f"Review the pull request for issue #{issue_number}: {issue_title}.\n"
            f"Check for: correctness, test coverage, security issues, code style.\n"
            f"Provide a summary of your findings."
        )
        ctx = RunContext(
            workspace_path=workspace_path,
            branch=branch,
            issue_title=f"Review: {issue_title}",
        )
        session = await self._provider.start_session(ctx)

        review_text_parts = []
        async for event in self._provider.run_turn(session, review_prompt):
            if event.type == EventType.MESSAGE_DELTA:
                text = event.data.get("text", "")
                if text:
                    review_text_parts.append(text)

        review_text = "\n".join(review_text_parts)

        # Post review as comment
        comment = f"## JHSymphony Code Review\n\n{review_text}\n\n---\n*Reviewed by JHSymphony*"
        await self._tracker.post_comment(issue_number, comment)

        return ReviewResult(
            pr_number=pr_number,
            pr_url=pr_url,
            review_text=review_text,
            approved=self._auto_approve,
        )
